### ISSUE TITLE
diagrams doesn't install with ghc 8.4.2

### ISSUE THREAD

**Issue by GeorgeCo** [diagrams/diagrams#16]
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.2
 cabal install -j5 diagrams
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: diagrams-1.4 (user goal)
[__1] trying: diagrams:+svg
[__2] trying: diagrams-svg-1.4.1.1 (dependency of diagrams +svg)
[__3] next goal: base (dependency of diagrams-svg)
[__3] rejecting: base-4.11.1.0/installed-4.1... (conflict: diagrams-svg =>
base>=4.3 && <4.11)
[__3] rejecting: base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0,
base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, diagrams, diagrams-svg,
diagrams:svg, diagrams-cairo, diagrams-lib

**Comment by byorgey** [comment]
Thanks for the report!  We are steadily working on getting everything updated and it should be all set to go very soon.

**Comment by byorgey** [comment]
I believe everything should be updated now!
