### ISSUE TITLE
Can one place LaTeX in a diagram?

### ISSUE THREAD

**Issue by mherzl** [diagrams/diagrams#19]
I see that one can place [text in a diagram](https://archives.haskell.org/projects.haskell.org/diagrams/haddock/Diagrams-TwoD-Text.html), and that one can [place a diagram into LaTeX](https://archives.haskell.org/projects.haskell.org/diagrams/doc/latex.html).

Is there some way to place LaTeX into a diagram?

**Comment by byorgey** [comment]
Yes, although only if you are using the `diagrams-pgf` backend.  See [section 6 of the LaTeX tutorial](https://archives.haskell.org/projects.haskell.org/diagrams/doc/latex.html#tips-and-tricks).  Let us know if that answers your question!
