### ISSUE TITLE
cabal install needs the --lib flag

### ISSUE THREAD

**Issue by technocrat** [diagrams/diagrams#22]
```
$ ~/hs$ cabal install diagrams
Resolving dependencies...
Up to date
Warning: You asked to install executables, but there are no executables in
target: diagrams. Perhaps you want to use --lib to install libraries instead.
```
Installs successfullyu with 

`$ cabal install --lib diagrams
`
Build profile: -w ghc-8.8.3 -O1

**Comment by byorgey** [comment]
Thanks for the report!  Could you tell us where you saw the instructions to do `cabal install diagrams`?  I'm sure there are a lot of places we need to update it.  I guess the behavior of `cabal` has changed.

**Comment by technocrat** [comment]
README.markdown
lines 13, 45

diagrams.cabal
line 10

Not sure how it's implicated, if at all, in travis_yml

**Comment by igormoreno** [comment]
All the installation instructions in the [User Manual](https://diagrams.github.io/doc/manual.html) and the [Quick Start](https://diagrams.github.io/doc/quickstart.html) tutorial are also affected.
