### ISSUE TITLE
Is this package actively maintained?

### ISSUE THREAD

**Issue by ezzieyguywuf** [diagrams/diagrams#25]
I see that it references older versions, for example `diagrams-postscript` is up to version `1.5` but this package does not pull it in.

If it is intended to keep this package active can you please bump the upper bounds? This would allow us to continue packaging it in gentoo.

**Comment by byorgey** [comment]
It is intended to be, but I admit that the maintenance has not been very active recently at all.  Once the semester gets underway in a week or so one thing I plan to do is to put some more time into updating and making new releases of diagrams packages.

**Comment by ezzieyguywuf** [comment]
> It is intended to be, but I admit that the maintenance has not been very active recently at all

Thank you for your work, although I have not personally used the `diagrams-*` ecosystem of packages, I can see that some good and hard work has gone into it, and I have heard great things :)
