### ISSUE TITLE
Allow diagrams-core 1.5

### ISSUE THREAD

**Issue by sternenseemann** [diagrams/diagrams#26]
Seems there are no issues with compilation currently, but would maybe require a major version bump?

**Comment by byorgey** [comment]
Yes, first I want to make sure all the packages this pulls in are updated for the latest GHC (which was the reason for the release of diagrams-core 1.5).  diagrams-core-1.5 has no new features over 1.4.x so there's no particular rush.

**Comment by byorgey** [comment]
Closed by 504c60b9cf92c5a55b76f41040e450eaa7a424bc .
