### ISSUE TITLE
Any references on the theory behind diagrams?

### ISSUE THREAD

**Issue by davibarreira** [diagrams/diagrams#32]
Hey, this package is amazing. I'm developing something similar for my PhD. I'd love to learn more about the theory behind the package. I'm developing something more math oriented, yet, since this is in Haskell, I imagine that there has been a lot of thought behind the category theoretical aspects of the package.

Hence, I was wondering if there is a paper or something besides the docs that go into more theoretical aspects.

**Comment by byorgey** [comment]
Hi @davibarreira , glad you're enjoying it!  You can find a couple things about diagrams in my list of publications here: http://ozark.hendrix.edu/~yorgey/publications.html .  Specifically, check out "Monoids: Theme and Variations".  You will find a PDF and also slides and a video of my presentation at the Haskell Symposium.

**Comment by davibarreira** [comment]
Thanks for the fast response!
