### ISSUE TITLE
Please add support for latest versions of lens, linear, etc.

### ISSUE THREAD

**Issue by peti** [diagrams/diagrams#9]
diagrams-lib does not support recent versions of several of its dependencies: http://packdeps.haskellers.com/feed?needle=diagrams-lib. Would it be possible to get an update that remedies this issue?

**Comment by byorgey** [comment]
Just FYI, via Stackage and packdep's RSS feed, etc., many of us are automatically notified as soon as these dependency issues arise, and we are indeed aware of the specific dependencies that need updating at the moment.  We are all busy and it is just an issue of someone finding the time to update all the diagrams packages (some automation helps but it is still a somewhat tedious process).  Filing an issue here does not actually make this happen any faster.

**Comment by peti** [comment]
Having a ticket (that's closed when the issue is resolved) makes my life a lot easier because I don't have to busy-pull dozens of packages for updates to decide whether I can enable their builds in NixOS or not. If you don't want me to open a ticket for your libraries, however, then by all means I won't.

**Comment by byorgey** [comment]
Ah, I see.  Tell you what, I will just try to remember to ping you every time we do some dependency updates like this.  How does that sound?
